name: Docker CI + Sync to Hugging Face

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    name: Build Docker Image (Local Only)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Docker Image (No Push)
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: false
          tags: kamaleshbaskaran/student-score-prediction:latest

  sync-to-hub:
    name: Sync to Hugging Face Hub
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Configure Git and Push
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Kamaleshbaskaran"
          git remote set-url origin https://Kamaleshbaskaran:${HF_TOKEN}@huggingface.co/spaces/Kamaleshbaskaran/student-score-prediction
          git pull origin main --rebase || true
          git push origin main
